---
resource_types:
- name: git-branch-heads
  type: docker-image
  source:
    repository: vito/git-branch-heads-resource

resources:
- name: fly
  type: git-branch-heads
  source:
    uri: https://github.com/concourse/fly
    branches: [wip-*]

- name: atc
  type: git-branch-heads
  source:
    uri: https://github.com/concourse/atc
    branches: [wip-*]

- name: go-concourse
  type: git-branch-heads
  source:
    uri: https://github.com/concourse/go-concourse
    branches: [wip-*]

jobs:
- name: fly
  public: true
  plan:
  - get: fly
    trigger: true
    version: every
  - task: unit
    file: fly/ci/pr.yml

- name: atc
  public: true
  plan:
  - get: atc
    trigger: true
    version: every
  - task: unit
    file: atc/ci/pr.yml

- name: go-concourse
  public: true
  plan:
  - get: go-concourse
    trigger: true
    version: every
  - task: unit
    file: go-concourse/ci/pr.yml
    tags: [pr]
